const COUNTRIES_FETCH_REQUEST = 'countries/COUNTRIES_FETCH_REQUEST';
const COUNTRIES_FETCH_SUCCESS = 'countries/COUNTRIES_FETCH_SUCCESS';
const COUNTRIES_FETCH_ERROR = 'countries/COUNTRIESS_FETCH_ERROR';

export default {
  COUNTRIES_FETCH_REQUEST,
  COUNTRIES_FETCH_SUCCESS,
  COUNTRIES_FETCH_ERROR
};
